
#type: args

train:
  epochs: 200
  batch_size: 16 
  lr: 1.0e-3
  itr_per_epoch: 1.0e+8


diffusion:
  layers: 4 
  channels: 64 
  nheads: 8
  diffusion_embedding_dim: 128
  beta_start: 0.0001
  beta_end: 0.5
  num_steps: 50
  schedule: "quad"
  is_linear: False

model:
  is_unconditional: 0
  timeemb: 128
  featureemb: 16
  target_strategy: "random"
  test_missing_ratio: 1

more:
  S0: 100
  timestep: 300
  stimcount: 200007
  idea: 2
  line : "y"
  drift: 0.1
  sigma: 0.5
